"""Local-only browser UI for read-only Codex history."""

VAULT_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" href="data:,"><title>Codex Vault — Local history</title>
<style>
:root{color-scheme:dark;--bg:#080b10;--panel:#111722;--line:#344057;--text:#f7f8fa;--muted:#bdc7d8;--purple:#6042a6;--light:#d9cdff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#172038 0,transparent 36%),var(--bg);color:var(--text);font:500 16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
main{width:min(960px,calc(100% - 32px));margin:36px auto 80px}a{color:var(--light)}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:28px}h1{font-size:clamp(34px,7vw,58px);letter-spacing:-.045em;line-height:1;margin:10px 0}.lede,.muted{color:var(--muted)}.lede{font-size:18px;max-width:680px;margin:0}.panel{background:color-mix(in srgb,var(--panel) 95%,transparent);border:1px solid var(--line);border-radius:18px;padding:22px;margin:18px 0}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric{border:1px solid var(--line);border-radius:13px;padding:14px}.metric span{display:block;color:var(--muted);font-size:14px}.metric strong{font-size:22px}form,.actions{display:flex;gap:10px;flex-wrap:wrap}input,select,textarea,button,a.button{font:inherit;border-radius:10px;border:1px solid #8996ad;padding:11px 14px}input,select,textarea{background:#080b10;color:var(--text);flex:1;min-width:220px}textarea{display:block;width:100%;resize:none}button,a.button{background:var(--purple);color:white;font-weight:750;cursor:pointer;text-decoration:none}button.secondary,a.secondary{background:transparent}button:disabled,select:disabled{opacity:.55;cursor:wait}.result{width:100%;text-align:left;background:#151d2a;margin:10px 0;padding:15px;line-height:1.45}.result small{display:block;color:var(--muted);margin-bottom:5px}.entry{border-top:1px solid var(--line);padding:20px 0}.entry:first-child{border-top:0}.entry h3{margin:0 0 4px;font-size:17px}.entry time{display:block;color:var(--muted);font-size:14px;margin-bottom:10px}.entry p{white-space:pre-wrap;overflow-wrap:anywhere;margin:0}#error,#backup-error,#schedule-error,#restore-error{color:#ffc3c8}#status,#backup-status,#schedule-status,#restore-status{color:var(--muted)}#recovery{border-left:4px solid var(--light);padding-left:16px;margin-top:18px}.subsection{border-top:1px solid var(--line);margin-top:22px;padding-top:18px}[hidden]{display:none!important}
@media(max-width:620px){header{display:block}.summary{grid-template-columns:1fr}.panel{padding:16px}main{margin-top:22px}}
@media print{body{background:white;color:black}header,.summary,#backup-panel,#restore-panel,#search-panel,#results-panel,.actions,#error,#status{display:none!important}main{width:auto;margin:0}.panel{border:0;padding:0;background:white}.entry{break-inside:avoid;border-color:#bbb}.entry time{color:#444}}
</style></head><body><main>
<header><div><a id="back" href="/">← Migration</a><h1>Codex Vault</h1><p class="lede">Back up, find, and export the Codex conversations stored on this Mac.</p></div></header>
<section class="summary" aria-label="Local history summary">
  <div class="metric"><span>Active conversations</span><strong id="active">—</strong></div>
  <div class="metric"><span>Archived conversations</span><strong id="archived">—</strong></div>
  <div class="metric"><span>Transcript data</span><strong id="bytes">—</strong></div>
</section>
<section class="panel" id="backup-panel"><h2>Back up this history</h2><p class="muted">Choose an empty local or cloud-sync folder, or your existing Vault. Conversation content is encrypted before it is written there.</p><div class="actions"><input id="vault-folder" readonly placeholder="Choose a Vault folder"><button id="choose-vault" class="secondary">Choose folder…</button><button id="backup" disabled>Create encrypted backup</button></div><p id="backup-status" role="status" aria-live="polite"></p><p id="backup-error" role="alert"></p><div id="recovery" hidden><h3>Save this recovery key</h3><p>Put it in your password manager. It is required if this Mac is lost, and it is not stored in the backup folder.</p><textarea id="recovery-key" readonly rows="3"></textarea><div class="actions"><button id="copy-recovery">Copy recovery key</button><button id="saved-recovery" class="secondary">I saved it</button></div></div><div class="subsection"><h3>Automatic backup</h3><p class="muted">After the first verified backup, this Mac can add a new encrypted snapshot every day—even when the app is closed. Existing snapshots are kept.</p><div class="actions"><button id="enable-schedule" disabled>Turn on daily backup</button><button id="disable-schedule" class="secondary" hidden>Turn off automatic backup</button></div><p id="schedule-status" role="status" aria-live="polite"></p><p id="schedule-error" role="alert"></p></div></section>
<section class="panel" id="restore-panel"><h2>Recover a backup</h2><p class="muted">Choose a backup version and recover it into an empty folder. This does not replace your live Codex data or change what appears in Codex. Inspect the recovered copy before any later install.</p><div class="actions"><input id="restore-vault" readonly placeholder="Choose an existing Vault"><button id="choose-restore-vault" class="secondary">Choose Vault…</button></div><div class="actions"><select id="restore-snapshot" aria-label="Backup version" disabled><option value="">Choose a Vault to see backups</option></select></div><div class="actions"><input id="restore-output" readonly placeholder="Choose an empty recovery folder"><button id="choose-restore-output" class="secondary">Choose empty folder…</button><button id="restore" disabled>Recover this backup</button></div><p id="restore-status" role="status" aria-live="polite"></p><p id="restore-error" role="alert"></p></section>
<section class="panel" id="search-panel"><h2>Search local history</h2><form id="search"><label class="muted" for="query">Words or phrase</label><input id="query" required autocomplete="off"><button type="submit">Search</button></form><p class="muted">The first version searches transcript files directly, so a very large history can take time. A private local index will make this faster later.</p></section>
<section class="panel" id="results-panel" hidden><h2>Results</h2><div id="results"></div></section>
<section class="panel" id="thread" hidden><div class="actions"><button id="download">Download Markdown</button><button id="print" class="secondary">Print / Save PDF</button><button id="share" class="secondary">Share thread…</button></div><p class="muted" id="thread-meta"></p><div id="entries"></div></section>
<p id="status" role="status" aria-live="polite">Loading history…</p><p id="error" role="alert"></p>
</main><script>
const $=id=>document.getElementById(id);
const tokenKey="codex-migrate-token:"+location.origin;
const incoming=new URLSearchParams(location.hash.slice(1)).get("token");
if(incoming)sessionStorage.setItem(tokenKey,incoming);
const token=incoming||sessionStorage.getItem(tokenKey)||"";
history.replaceState(null,"",location.pathname);
$("back").href="/#token="+encodeURIComponent(token);
const fmt=n=>{const units=["B","KB","MB","GB","TB"];let i=0;while(n>=1000&&i<units.length-1){n/=1000;i++}return `${n.toFixed(n>=100?0:n>=10?1:2)} ${units[i]}`};
async function api(path,data){const response=await fetch(path,{method:data===undefined?"GET":"POST",headers:{"X-Codex-Migrate-Token":token,"Content-Type":"application/json"},...(data===undefined?{}:{body:JSON.stringify(data)})});const type=response.headers.get("Content-Type")||"";const body=type.includes("application/json")?await response.json():await response.text();if(!response.ok)throw Error(body.error||"The local request failed");return body}
function fail(error){$("error").textContent=error.message;$("status").textContent=""}
let selected=null;
function params(item){return new URLSearchParams({collection:item.collection,transcript:item.transcript})}
async function openThread(item){$("error").textContent="";$("status").textContent="Opening conversation…";try{const thread=await api("/api/vault/thread?"+params(item));selected=item;$("thread-meta").textContent=`${thread.collection} · ${thread.entries.length} readable entries`;$("entries").replaceChildren(...thread.entries.map((entry,index)=>{const article=document.createElement("article");article.className="entry";const h=document.createElement("h3");h.textContent=entry.role||`Entry ${index+1}`;article.append(h);if(entry.timestamp){const time=document.createElement("time");time.textContent=entry.timestamp;article.append(time)}const p=document.createElement("p");p.textContent=entry.text;article.append(p);return article}));$("thread").hidden=false;$("status").textContent="";$("thread").scrollIntoView({behavior:"smooth"})}catch(error){fail(error)}}
$("search").onsubmit=async event=>{event.preventDefault();$("error").textContent="";$("status").textContent="Searching local transcripts…";$("thread").hidden=true;try{const query=$("query").value.trim();const data=await api("/api/vault/search?"+new URLSearchParams({q:query,limit:"50"}));$("results").replaceChildren(...data.results.map(item=>{const button=document.createElement("button");button.type="button";button.className="result";const small=document.createElement("small");small.textContent=`${item.collection}${item.timestamp?" · "+item.timestamp:""}`;const text=document.createElement("span");text.textContent=item.snippet;button.append(small,text);button.onclick=()=>openThread(item);return button}));$("results-panel").hidden=false;$("status").textContent=data.results.length?`${data.results.length} result${data.results.length===1?"":"s"}. Select one to open it.`:"No matching conversation text found."}catch(error){fail(error)}};
async function markdownFile(){if(!selected)throw Error("Open a conversation first");const text=await api("/api/vault/export?"+params(selected));return new File([text],"codex-conversation.md",{type:"text/markdown"})}
$("download").onclick=async()=>{try{const file=await markdownFile(),url=URL.createObjectURL(file),link=document.createElement("a");link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){fail(error)}};
$("print").onclick=()=>window.print();
$("share").onclick=async()=>{try{const file=await markdownFile();if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:"Codex conversation",files:[file]});$("status").textContent="Share sheet opened."}else{$("status").textContent="This browser cannot open the share sheet. Use Download Markdown, then share or email the file."}}catch(error){if(error.name!=="AbortError")fail(error)}};
let backupTimer=null;
let verifiedBackup=false;
function backupView(data){const running=data.status==="running";if(data.destination&&!$("vault-folder").value)$("vault-folder").value=data.destination;if(data.destination&&!$("restore-vault").value){$("restore-vault").value=data.destination;refreshSnapshots()}verifiedBackup=data.status==="completed"&&!data.recovery_key;$("choose-vault").disabled=running;$("backup").disabled=running||!$("vault-folder").value||Boolean(data.recovery_key);$("backup-error").textContent=data.status==="failed"?(data.error||"Encrypted backup stopped safely."):"";if(running){const files=`${data.completed_files||0} of ${data.total_files||0} files`;const bytes=data.total_bytes?` · ${Math.round(100*(data.completed_bytes||0)/data.total_bytes)}% of ${fmt(data.total_bytes)}`:"";$("backup-status").textContent="Encrypting and verifying… "+files+bytes}else if(data.status==="completed"){$("backup-status").textContent=`Verified snapshot complete · ${data.transcript_files.toLocaleString()} files · ${fmt(data.transcript_bytes)}`}else if(data.status==="failed"){$("backup-status").textContent=""}else{$("backup-status").textContent="No backup is running."}if(data.recovery_key){$("recovery-key").value=data.recovery_key;$("recovery").hidden=false}else{$("recovery-key").value="";$("recovery").hidden=true}if(running&&!backupTimer)backupTimer=setInterval(refreshBackup,1500);if(!running&&backupTimer){clearInterval(backupTimer);backupTimer=null}refreshScheduleButton();refreshRestoreButton()}
async function refreshBackup(){try{backupView(await api("/api/vault/backup-status"))}catch(error){$("backup-error").textContent=error.message}}
$("choose-vault").onclick=async()=>{try{$("backup-error").textContent="";const result=await api("/api/vault/folder",{});if(result.path){$("vault-folder").value=result.path;$("restore-vault").value=result.path;verifiedBackup=false;$("backup").disabled=false;$("backup-status").textContent="Folder selected. Create backup when ready.";refreshScheduleButton();await refreshSnapshots()}}catch(error){$("backup-error").textContent=error.message}};
$("backup").onclick=async()=>{try{$("backup-error").textContent="";backupView(await api("/api/vault/backup",{destination:$("vault-folder").value,apply:true}))}catch(error){$("backup-error").textContent=error.message}};
$("copy-recovery").onclick=async()=>{try{await navigator.clipboard.writeText($("recovery-key").value);$("backup-status").textContent="Recovery key copied. Save it in your password manager."}catch(error){$("backup-error").textContent="Copy failed. Select the recovery key and copy it manually."}};
$("saved-recovery").onclick=async()=>{try{const result=await api("/api/vault/recovery-saved",{});backupView(result);$("backup-status").textContent=result.status==="completed"?"Recovery key acknowledged. The verified backup is ready.":"Recovery key acknowledged. Retry the encrypted backup."}catch(error){$("backup-error").textContent=error.message}};
let scheduleEnabled=false;
function refreshScheduleButton(){$("enable-schedule").hidden=scheduleEnabled;$("disable-schedule").hidden=!scheduleEnabled;$("enable-schedule").disabled=!verifiedBackup||!$("vault-folder").value}
function scheduleView(data){scheduleEnabled=Boolean(data.enabled);if(data.vault&&!$("vault-folder").value)$("vault-folder").value=data.vault;if(data.vault&&!$("restore-vault").value){$("restore-vault").value=data.vault;refreshSnapshots()}$("schedule-error").textContent=data.error||"";if(!data.enabled){$("schedule-status").textContent="Automatic backup is off."}else if(data.healthy){let detail="Daily encrypted backup is on.";if(data.last_run?.status==="completed")detail+=" Last backup completed "+(data.last_run.completed_at||"")+".";else if(data.last_run?.status==="failed")detail+=" The last automatic backup needs attention.";$("schedule-status").textContent=detail}else{$("schedule-status").textContent="Automatic backup needs attention."}refreshScheduleButton();refreshRestoreButton()}
async function refreshSchedule(){try{scheduleView(await api("/api/vault/schedule"))}catch(error){$("schedule-error").textContent=error.message}}
$("enable-schedule").onclick=async()=>{try{$("schedule-error").textContent="";$("enable-schedule").disabled=true;scheduleView(await api("/api/vault/schedule",{destination:$("vault-folder").value,interval_hours:24,apply:true}))}catch(error){$("schedule-error").textContent=error.message;refreshScheduleButton()}};
$("disable-schedule").onclick=async()=>{try{$("schedule-error").textContent="";scheduleView(await api("/api/vault/schedule-remove",{apply:true}))}catch(error){$("schedule-error").textContent=error.message}};
let restoreTimer=null;
function refreshRestoreButton(){$("restore").disabled=!$("restore-vault").value||!$("restore-snapshot").value||!$("restore-output").value}
async function refreshSnapshots(){const vault=$("restore-vault").value;const select=$("restore-snapshot");const selected=select.dataset.requested||select.value;select.dataset.ready="";select.disabled=true;select.replaceChildren(new Option(vault?"Loading backup history…":"Choose a Vault to see backups",""));refreshRestoreButton();if(!vault)return;try{const data=await api("/api/vault/snapshots?vault="+encodeURIComponent(vault));if(!data.snapshots.length){select.replaceChildren(new Option("No published backups found",""));return}select.replaceChildren(...data.snapshots.map(item=>{const when=new Date(item.created_at);const label=(Number.isNaN(when.getTime())?item.created_at:when.toLocaleString())+(item.latest?" · Latest":"");return new Option(label,item.snapshot_id)}));if(selected&&[...select.options].some(option=>option.value===selected))select.value=selected;select.dataset.ready="true";select.disabled=false;$("restore-error").textContent=""}catch(error){select.replaceChildren(new Option("Backup history unavailable",""));$("restore-error").textContent=error.message}finally{refreshRestoreButton()}}
function restoreView(data){const running=data.status==="running";if(data.snapshot||data.snapshot_id)$("restore-snapshot").dataset.requested=data.snapshot||data.snapshot_id;if(data.vault&&!$("restore-vault").value){$("restore-vault").value=data.vault;refreshSnapshots()}if(data.output&&!$("restore-output").value)$("restore-output").value=data.output;$("choose-restore-vault").disabled=running;$("choose-restore-output").disabled=running;$("restore-snapshot").disabled=running||$("restore-snapshot").dataset.ready!=="true";$("restore").disabled=running||!$("restore-vault").value||!$("restore-snapshot").value||!$("restore-output").value;$("restore-error").textContent=data.status==="failed"?(data.error||"Recovery stopped safely."):"";if(running){$("restore-status").textContent="Verifying and recovering the selected backup…"}else if(data.status==="completed"){$("restore-status").textContent=`Recovered copy ready · ${data.transcript_files.toLocaleString()} files · ${fmt(data.transcript_bytes)}`}else if(data.status==="failed"){$("restore-status").textContent=""}else{$("restore-status").textContent="No recovery is running."}if(running&&!restoreTimer)restoreTimer=setInterval(refreshRestore,1500);if(!running&&restoreTimer){clearInterval(restoreTimer);restoreTimer=null}}
async function refreshRestore(){try{restoreView(await api("/api/vault/restore-status"))}catch(error){$("restore-error").textContent=error.message}}
$("choose-restore-vault").onclick=async()=>{try{$("restore-error").textContent="";const result=await api("/api/vault/folder",{});if(result.path){$("restore-vault").value=result.path;await refreshSnapshots()}}catch(error){$("restore-error").textContent=error.message}};
$("choose-restore-output").onclick=async()=>{try{$("restore-error").textContent="";const result=await api("/api/vault/restore-folder",{});if(result.path){$("restore-output").value=result.path;refreshRestoreButton()}}catch(error){$("restore-error").textContent=error.message}};
$("restore-snapshot").onchange=refreshRestoreButton;
$("restore").onclick=async()=>{try{$("restore-error").textContent="";restoreView(await api("/api/vault/restore",{vault:$("restore-vault").value,output:$("restore-output").value,snapshot:$("restore-snapshot").value,apply:true}))}catch(error){$("restore-error").textContent=error.message}};
api("/api/vault/summary").then(data=>{$("active").textContent=data.active_transcripts.toLocaleString();$("archived").textContent=data.archived_transcripts.toLocaleString();$("bytes").textContent=fmt(data.transcript_bytes);$("status").textContent="Ready."}).catch(fail);
refreshBackup();
refreshSchedule();
refreshRestore();
</script></body></html>'''
